### PR TITLE
Add support for Laravel 6.1 and 6.4

### PR DESCRIPTION
**Pull request by jochensengier**

### CODE REVIEW

**Comment by booni3** [comment]
At the speed Laravel is now upgrading and is now semantic versioning, could the package switch to a caret composer version constraint i.e. ^6.0

**Comment by m2de** [comment]
Any chance of getting this merged in pretty please? Keeps causing issues since Laravel has moved to semantic versioning.

**Comment by spaceemotion** [comment]
This PR is already out of date, since Laravel is already at 6.5, so the solution of using a caret (https://github.com/dannyvankooten/laravel-vat/pull/20#issuecomment-547082060) might work best.

**Comment by m2de** [comment]
Ok, Have opened a new PR #21

**Pull request merged**
